# Generated by Django 3.2.13 on 2022-04-27 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_complete', models.BooleanField(default=False)),
                ('task_title', models.CharField(max_length=100)),
                ('task_goal', models.CharField(max_length=100)),
                ('task_duration', models.CharField(max_length=100)),
                ('task_content', models.TextField()),
                ('task_note', models.TextField()),
            ],
            options={
                'db_table': 'task',
            },
        ),
    ]
